### ISSUE TITLE
如何关闭某项功能？

### ISSUE THREAD

**Issue by 1052726643** [Kyouichirou/D7E1293#1]
您好，首先很感谢编写这个脚本。
不知道可不可以关闭或是修改“页面内容文字辅助颜色”功能，个人感觉文字拆分太过零散会导致颜色杂乱，反倒不利于阅读。

**Comment by Kyouichirou** [comment]
感谢反馈, 后面更新会考虑加上关闭功能, 临时可以在代码(Ctrl + F找到) `let holder = document.getElementsByClassName` 上一行添加 `return;`

**Comment by Kyouichirou** [comment]
感谢反馈, 后面更新会考虑加上关闭功能, 临时可以在代码(Ctrl + F找到) `let holder = document.getElementsByClassName` 上一行添加 `return;`
